### ISSUE TITLE
BUG: same file name in the same root

### ISSUE THREAD

**Issue by nogahaskal** [meateam/drive-project#70]
you can create a file with the same name under another directory and then move it to the same directory.
this will cause to files under the same directory with the same name.

ToDo:

- [ ] create tests that fails by the bug
- [x] find the bug cause
- [ ] create a fix

**Comment by AllKinds** [comment]
The bug was created [here](https://github.com/meateam/file-service/pull/175/commits/8be6e5ea4691d0475d1cbd2df51083bff67035ce) to handle floating files (that can have identical names).
To counter that a `pre save` hook was created but a `pre update` one was not.

The index should handle this, and be unique.

**Comment by AllKinds** [comment]
Should be solved by #90
